### ISSUE TITLE
Aggregate Document Generation errors with 500 "System.NullReferenceException: Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by jepthy** [Burgyn/MMLib.SwaggerForOcelot#183]
**Describe the bug**
Trying to create documentation for Aggregates in Ocelot.  When browsing in Swagger to the Aggregates documentation, it generates the following error:
`An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
at MMLib.SwaggerForOcelot.Aggregates.RouteDocs.CreateContent(Response response)
at MMLib.SwaggerForOcelot.Aggregates.RouteDocs.GetResponse()
at MMLib.SwaggerForOcelot.Aggregates.AggregateRouteDocumentationGenerator.CreateResponseSchema(IEnumerable`1 routes, SwaggerAggregateRoute aggregateRoute, OpenApiDocument openApiDocument)
at MMLib.SwaggerForOcelot.Aggregates.AggregateRouteDocumentationGenerator.GenerateDocs(SwaggerAggregateRoute aggregateRoute, IEnumerable`1 routes, OpenApiDocument openApiDocument)
at MMLib.SwaggerForOcelot.Aggregates.AggregateRouteDocumentationGenerator.GenerateDocs(SwaggerAggregateRoute aggregateRoute, OpenApiDocument openApiDocument)
at MMLib.SwaggerForOcelot.Aggregates.AggregatesDocumentFilter.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
at MMLib.SwaggerForOcelot.Middleware.SwaggerForOcelotMiddleware.Invoke(HttpContext context, ISwaggerEndPointProvider swaggerEndPointRepository, IDownstreamSwaggerDocsRepository downstreamSwaggerDocs)
at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Expected behavior**
Expect Aggregate documentation to show in Swagger

**To Reproduce**
This is using SwaggerForOcelot 4.4.1.
Demo project can be found here: https://github.com/jepthy/microservices (I have granted access to this repository)
Open project, and run the Docker-Compose project in Visual Studio.
Browse to http://localhost:9110/swagger/index.html?urls.primaryName=Aggregates
You will notice in the Docker instance it will list the errors in the console.

**Comment by Burgyn** [comment]
Hi.  I am currently vacating.  I'll look into it next week.

**Comment by jepthy** [comment]
Wonderful, thank you so much. Please let me know if you run into any issues pulling the sample project, etc.
    On Tuesday, August 17, 2021, 12:16:44 PM MDT, Miňo Martiniak ***@***.***> wrote:  
 
 


Hi. I am currently vacating. I'll look into it next week.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Burgyn** [comment]
Hi,

thanks for your sample. It helped me figure out where the problem was.

Your documentation of downstream services does not contain content of path response. I fixed the generation of documentation to take into account this case as well. 
Please try version `4.4.2`.

> 🍻 Thanks for helping to improve this package.

**Comment by jepthy** [comment]
Oh interesting, I wonder why it isn’t documenting the responses.  I will have to check that out, I was using the WebAPI template for VS with Swagger. Thank you so much for looking at this!


Sent from Yahoo Mail for iPhone


On Tuesday, August 24, 2021, 2:57 AM, Miňo Martiniak ***@***.***> wrote:




Hi,

thanks for your sample. It helped me figure out where the problem was.

Your documentation of downstream services does not contain content of path response. I fixed the generation of documentation to take into account this case as well.
Please try version 4.4.2.


 🍻 Thanks for helping to improve this package.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
